<div class="row mb-4">
    <div class="col-md-8">
        <h1>📚 Recipe Catalogs</h1>
        <p class="text-muted">Manage your digitized cookbooks.</p>
    </div>
    <div class="col-md-4 text-end">
        <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#importForm">
            + Import Catalog
        </button>
    </div>
</div>

<div class="collapse mb-4" id="importForm">
    <div class="card card-body bg-light">
        <h5>Import Existing JSON Catalog</h5>
        <form action="<?= url('/catalogs/import') ?>" method="POST" enctype="multipart/form-data">
            <div class="input-group">
                <input type="file" name="catalog_file" class="form-control" accept=".json" required>
                <button class="btn btn-success" type="submit">Upload & Import</button>
            </div>
            <div class="form-text">Upload a .json file generated by the cataloger script.</div>
        </form>
    </div>
</div>

<div class="row">
    <?php if (empty($catalogs)): ?>
        <div class="col-12 text-center py-5">
            <div class="api-placeholder">
                <p class="lead">No catalogs found.</p>
                <p>Use the import button above to add your first catalog!</p>
            </div>
        </div>
    <?php else: ?>
        <?php foreach ($catalogs as $catalog): ?>
            <div class="col-md-6 mb-4">
                <div class="card h-100 shadow-sm">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start">
                            <h5 class="card-title"><?= h($catalog['name']) ?></h5>
                            <span class="badge bg-info"><?= $catalog['recipe_count'] ?> recipes</span>
                        </div>
                        <h6 class="card-subtitle mb-2 text-muted">
                            <?= h($catalog['model_used'] ?? 'Unknown Model') ?>
                        </h6>
                        <p class="card-text small text-muted">
                            Source: <?= h(basename($catalog['source_folder'] ?? 'Unknown')) ?>
                        </p>
                    </div>
                    <div class="card-footer bg-transparent border-top-0">
                        <a href="<?= url('/catalogs/' . $catalog['id']) ?>" class="btn btn-sm btn-outline-primary">View
                            Details</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>